"""empty message

Revision ID: 457e9e3b10fd
Revises: 
Create Date: 2022-07-20 00:44:14.354442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e9e3b10fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_table')
    # ### end Alembic commands ###
