"""empty message

Revision ID: 7b3033ea61b6
Revises: a8ade16fb5b8
Create Date: 2022-07-24 14:07:28.318564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3033ea61b6'
down_revision = 'a8ade16fb5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('info_table', sa.Column('count_of_dimension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_table', 'count_of_dimension')
    op.drop_table('dimension')
    # ### end Alembic commands ###
