"""empty message

Revision ID: a8ade16fb5b8
Revises: 457e9e3b10fd
Create Date: 2022-07-20 00:57:21.201776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ade16fb5b8'
down_revision = '457e9e3b10fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_table', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_table', 'password')
    # ### end Alembic commands ###
